apiVersion: v1
kind: ConfigMap
metadata:
  name: udagram-aws
data:
  credentials: |
    [default]
    aws_access_key_id=ASIAXTABYBZMDSO7U4CH
    aws_secret_access_key=AixYT46AHE8GY3gUMZFd7z8WTM76+ekZqVig8RVf
    aws_session_token=AixYT46AHE8GY3gUMZFd7z8WTM76+ekZqVig8RVf
export AWS_SESSION_TOKEN=FwoGZXIvYXdzECcaDC2kscs2kDQkOx3F0yLVAU8dDiagROAQamCYR1iCgd9vNry47ewIjcjiWB6mDWRHIk1Rwz/+gG1OMbo2ZasdyvGrZbrILlULT6Gb2BQiAUpR+SZ9rI59/Hj3oS1yXWVz/vUZilKdm7csusJ/KMYKpqgGmuZNmLnUyFrw2O9fj0qho/rfSODdLr4EwaNiDaOxBcxJNM8cvp81DieK3JhsJVCjPRoIJB1PDJPEmnKsoVnBrqw9GvqsBBej+nPdKis7NmPLVi8pAr4EVAKF5XjE/FGyy6X3iakNtYCOBOXwyR0NVbGPCSibpfSZBjItYt6y1PQmi9Sz8gqJXTAayaSQNEcbmwPV8v4xSwS7i909Z00BZRh2soWw6opj

 