# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3 
    - run: docker-compose -f docker-compose-build.yaml build --parallel
    - run: docker tag udagram-frontend:local toyintheisaac/udagram-frontend:v2
    - run: docker tag udagram-api-user toyintheisaac/udagram-api-user:v1
    - run: docker tag udagram-api-feed toyintheisaac/udagram-api-feed:v1
    - run: docker tag reverseproxy toyintheisaac/reverseproxy:v1
    - run: echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u "${{secrets.DOCKER_USERNAME}}" --password-stdin
    - run: docker push toyintheisaac/udagram-frontend:v2
    - run: docker push toyintheisaac/udagram-api-user:v1
    - run: docker push toyintheisaac/udagram-api-feed:v1
    - run: docker push toyintheisaac/reverseproxy:v1
